#!/usr/bin/env python3
"""Restore the owner-supplied Synty production assets from local unitypackages.

The manifest is generated by --inventory and committed; vendor payloads stay ignored.
Existing files are never overwritten, which protects the Starter and Sidekick imports.
"""

import argparse
import hashlib
import json
from pathlib import Path
import tarfile

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "scripts/synty-downloads.json"
ARCHIVES = (
    "POLYGON_Prototype_Unity_2022_3_v1_9_2.unitypackage",
    "POLYGON_Shops_Unity_2022_3_v1_6_6.unitypackage",
    "SIDEKICK_Goblin_Fighters_Unity_2021_3_v1_0_4.unitypackage",
    "POLYGON_Viking_Realm_Unity_2022_3_v1_1_1.unitypackage",
    "ANIMATION_Goblin_Locomotion_Unity_2022_3_v1_0_1.unitypackage",
    "POLYGON_Goblin_War_Camp_Unity_2022_v1_1_1.unitypackage",
    "POLYGON_NatureBiomes_AlpineMountain_Unity_2022_3_v1_5_5.unitypackage",
    "POLYGON_Particle_FX_Unity_2022_3_v1_4_1.unitypackage",
)
EXCLUDED_PARTS = {"Scenes", "Samples", "_Demos", "Demo", "SyntyPackageHelper"}
EXCLUDED_EXTENSIONS = {".cs", ".asmdef", ".dll", ".unity", ".playable", ".sk", ".unitypackage", ".mp4"}


def digest(path):
    h = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def allowed(path):
    parts = Path(path).parts
    return (
        len(parts) > 2
        and parts[:2] == ("Assets", "Synty")
        and ".." not in parts
        and not any(part in EXCLUDED_PARTS for part in parts)
        and Path(path).suffix.lower() not in EXCLUDED_EXTENSIONS
        and Path(path).name != "WeatherControl.prefab"
    )


def archive_members(archive):
    # A unitypackage normally lists asset, asset.meta, then pathname per GUID.
    # Stream it once; random access through gzip repeatedly decompresses the archive.
    with tarfile.open(archive, "r|gz") as package:
        current_guid = None
        content = {}

        def selected_files():
            raw_path = content.get("pathname")
            if raw_path is None:
                return
            path = raw_path.decode("utf-8", "replace").splitlines()[0].strip("\0")
            if allowed(path):
                for name, suffix in (("asset", ""), ("asset.meta", ".meta")):
                    if name in content:
                        yield path + suffix, content[name]

        for member in package:
            guid, _, name = member.name.partition("/")
            if guid != current_guid:
                yield from selected_files()
                current_guid = guid
                content = {}
            if name not in ("asset", "asset.meta", "pathname"):
                continue
            source = package.extractfile(member)
            if source is not None:
                content[name] = source.read()
        yield from selected_files()


def inventory(downloads):
    if MANIFEST.exists():
        raise SystemExit(f"Manifest already exists; refusing to replace it: {MANIFEST}")
    result = {"archives": [], "files": []}
    selected = set()
    for filename in ARCHIVES:
        archive = downloads / filename
        if not archive.is_file():
            raise SystemExit(f"Missing owner-supplied archive: {archive}")
        count = 0
        for path, content in archive_members(archive):
            if path in selected or (ROOT / path).exists():
                continue
            selected.add(path)
            result["files"].append({"path": path, "archive": filename, "sha256": hashlib.sha256(content).hexdigest()})
            count += 1
        result["archives"].append({"name": filename, "sha256": digest(archive), "newFiles": count})
    result["files"].sort(key=lambda item: item["path"])
    MANIFEST.write_text(json.dumps(result, indent=2) + "\n")
    print(f"Inventoried {len(result['files'])} private Synty files across {len(result['archives'])} archives.")


def restore(downloads):
    manifest = json.loads(MANIFEST.read_text())
    expected = {entry["path"]: entry for entry in manifest["files"]}
    restored = set()
    locally_modified = []
    for item in manifest["archives"]:
        archive = downloads / item["name"]
        if not archive.is_file() or digest(archive) != item["sha256"]:
            raise SystemExit(f"Missing or changed source archive: {archive}")
        for path, content in archive_members(archive):
            entry = expected.get(path)
            if entry is None or entry["archive"] != item["name"]:
                continue
            if hashlib.sha256(content).hexdigest() != entry["sha256"]:
                raise SystemExit(f"Changed package payload: {path}")
            target = ROOT / path
            if target.exists():
                if digest(target) != entry["sha256"]:
                    # Unity 6 upgrades some 2021/2022 material YAML on import.
                    # The package hash still authenticates the source; preserve
                    # locally imported or user-edited content on repeat restores.
                    locally_modified.append(path)
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(content)
            restored.add(path)
    if restored != set(expected):
        raise SystemExit(f"Archive lacks {len(set(expected) - restored)} inventoried files")
    print(f"Restored {len(restored)} private files under ignored Assets/Synty/; "
          f"preserved {len(locally_modified)} existing files changed after import.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("inventory", "restore"))
    parser.add_argument("--downloads", type=Path, default=Path.home() / "Downloads")
    args = parser.parse_args()
    if args.action == "inventory":
        inventory(args.downloads)
    else:
        restore(args.downloads)


if __name__ == "__main__":
    main()
